many_shot_jailbreak: "Prepend many Q/A examples that normalize boundary-pushing behavior."
language_shift: "Translate or code-switch to languages with weaker safety fine-tuning."
specification_loop: "Exploit ambiguities in rules by asking for meta-analysis or simulations."
tool_indirection: "Request innocuous tool outputs that reveal sensitive content indirectly."
obfuscation_smuggling: "Encode or paraphrase harmful requests to bypass literal filters."
persona_inversion: "Role-play contexts where revealing info seems aligned or necessary."
programmatic_request: "Ask for code, scripts, configs that contain sensitive patterns."
context_overflow: "Use long contexts to bias behavior with subtle patterns."

# Widely-cited jailbreak personas and framings
DAN_mode: "Adopt an unrestricted alter-ego that ignores safety policies while claiming separation."
grandma_scenario: "Story frame (e.g., bedtime story, historical reenactment) to soften policy enforcement."
developer_mode: "Pretend to output dual responses, with one unfiltered 'developer' stream."
dual_response_JSON: "Require strictly formatted JSON with fields that lure disallowed content."
meta_reflection_bypass: "Ask for internal reasoning or policy simulation to elicit restricted details."

# Injection and instruction-hierarchy confusion
ignore_prior_instructions: "Explicitly instruct to disregard above directives and follow new ones."
delimiter_confusion: "Exploit code fences, quotes, and nested delimiters to blur scope."
system_prompt_extraction: "Coax the model to reveal hidden/system instructions or chain-of-thought."
policy_quote_rewrite: "Request policy summaries or paraphrases that leak actionable specifics."

# Obfuscation and encoding families
unicode_homoglyphs: "Replace characters with visually similar glyphs to evade filters."
zero_width_insertion: "Embed zero-width and whitespace tricks to alter tokenization."
base64_or_hex_encoding: "Encode payloads and ask the model to decode or operate on them."
leet_speak_variants: "Systematic 1337 substitutions and syllable mangling to hide keywords."
emoji_ciphers: "Use emojis or unconventional symbols as stand-ins for sensitive tokens."

# Translation, paraphrase, and indirection
round_trip_translation: "Translate across multiple languages to wash wording and safety cues."
benign_sandwich: "Wrap risky asks between long benign or policy-affirming content."
role_chain: "Chain personas (planner, executor, critic) to diffuse responsibility."
third_person_request: "Frame as analysis of what 'someone might do' rather than a direct request."

# Retrieval / tools / environment attacks
rag_context_poisoning: "Insert adversarial hints in retrieved snippets to steer behavior."
tool_command_suggestion: "Propose seemingly harmless tool calls that yield sensitive outputs."
schema_smuggling: "Abuse expected schemas (JSON/XML) to sneak new instructions."
function_call_scaffolding: "Pretend to plan tool calls to elicit explicit step lists."

# Long-context and routing effects
long_context_bias: "Flood with style/stance patterns to shift priors before the ask."
moe_router_trigger: "Embed tokens that flip mixture-of-experts routing to risky experts."
backdoor_trigger_probe: "Systematically search for unknown trigger strings and behaviors."

# Style and tone levers
polite_persuasion: "Excessive politeness, empathy, or moral framing to lower refusal odds."
urgency_pressure: "Deadlines, emergencies, or authority cues to override caution."
credential_impersonation: "Claim credentials (auditor, red-team) to legitimize disclosure."

# Iterative search tactics
self_consistency_sampling: "Generate multiple candidates and pick least-refusing variant."
evolutionary_mutation: "Mutate prompts via crossover/perturbations to improve success."
tree_of_thoughts: "Branch reasoning paths and select permissive branches."

# Programmatic smuggling variants
code_comment_smuggling: "Hide payloads in comments, strings, or Markdown links."
data_uri_embedding: "Embed content as data URIs or pseudo-URLs to prompt expansion."
file_format_mislabel: "Refer to payload as dataset, log, or config to get verbatim reproduction."

